export const VALID_SALARY_HEADERS = [
  "Employee ID",
  "Full Name",
  "Annual CTC",
  "Basic Salary",
  "HRA",
  "LTA",
  "Other Allowances",
  "Incentives",
  "Overtime",
  "Statutory Bonus",
  "Bonus",
  "Advance Recovery",
  "Employee PF",
  "Employer PF",
  "ESIC Employee",
  "ESIC Employer",
  "Gratuity",
  "Professional Tax",
  "TDS",
  "Insurance Employee",
  "Insurance Employer",
  "Final CTC",
  "LOP Days",
  "LOP Deduction",
  "Gross Salary",
  "Net Salary",
  "Payslip Generated",
  "Status",
  "Payslip Generation"
];